### ISSUE TITLE
compatible with Linter?

### ISSUE THREAD

**Issue by pashute** [fundisoftware/linter-vnu#1]
Is linter-vnu compatible with Linter (which does a lint on javascript) or do I need to first remove Linter?

**Comment by GrahamHannington** [comment]
@pashute  wrote:

> Is linter-vnu compatible with Linter (which does a lint on javascript)

If we're referring to the same "Linter"—the Atom Linter package, `linter`—then: yes.

> or do I need to first remove Linter?

No.

From the `linter-vnu` [readme](https://github.com/fundisoftware/linter-vnu):

> The v.Nu linter is [...] a linter provider for the Atom Linter.
>
> **Requirements**
> - Atom Linter package (`linter`)

`linter-vnu` is not only _compatible_ with Linter; `linter-vnu` _requires_ Linter.

**Comment by pashute** [comment]
<embarrassment onclick="readDefinition('rtfm')">hides under the bed</embarrassment>

**Comment by pashute** [comment]
<embarrassment onclick="readDefinition('rtfm')">hides under the bed</embarrassment>

**Comment by GrahamHannington** [comment]
😄 

In truth, I haven't touched `linter-vnu` for a while. I developed it because I had a need for it at the time. I haven't needed it recently. I keep expecting someone to report that a change in Linter has broken `linter-vnu`, but that hasn't happened yet.
